// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlZzsKm2_-HMEesgTSVhwtfUyzD0pLUvI',
    appId: '1:499577384958:web:4ead92a48b0af2ab0e5aaf',
    messagingSenderId: '499577384958',
    projectId: 'cripto-monitor-app',
    authDomain: 'cripto-monitor-app.firebaseapp.com',
    storageBucket: 'cripto-monitor-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7ta6tsH9MonAqkDNyeNs6P55RJAXvUuU',
    appId: '1:499577384958:android:6b608d4cebee51400e5aaf',
    messagingSenderId: '499577384958',
    projectId: 'cripto-monitor-app',
    storageBucket: 'cripto-monitor-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RX5lrr94JJ6KIYTUi4oZV4BLFBxzXNg',
    appId: '1:499577384958:ios:aac45089b9662c3a0e5aaf',
    messagingSenderId: '499577384958',
    projectId: 'cripto-monitor-app',
    storageBucket: 'cripto-monitor-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlZzsKm2_-HMEesgTSVhwtfUyzD0pLUvI',
    appId: '1:499577384958:web:712047256a9a4aad0e5aaf',
    messagingSenderId: '499577384958',
    projectId: 'cripto-monitor-app',
    authDomain: 'cripto-monitor-app.firebaseapp.com',
    storageBucket: 'cripto-monitor-app.firebasestorage.app',
  );
}
